name: Vite build

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4.0.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: true
            - run: pnpm run build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
